### PR TITLE
CI: reenable test CANGPSCopterMission

### PR DESCRIPTION
**Pull request by robertlong13**
Now that the repo is public, this CI might pass. Never had it fail on a public repo, but almost always failed on this when private.

### CODE REVIEW

**Comment by robertlong13** [comment]
Still failing strangely. I've reduced the speedup from 5 to 3 and that seems to help. The errors we get are related to GPS delta not being tight enough, so reducing sim speedup will probably help. I'm going to re-run the test 10 times and make sure I get 10 passes in a row.

Also re-running on stock 4.5 on my personal fork to see if I've been remembering correctly about this passing on stock 4.5

**Comment by robertlong13** [comment]
Okay, stock 4.5 branch _did_ have this problem for me. That's a good datapoint: https://github.com/robertlong13/ardupilot/actions/runs/12228798129/job/34108541147

**Comment by robertlong13** [comment]
Aha! Latest backports for 4.5 had the same failure too! https://github.com/ArduPilot/ardupilot/actions/runs/12090226251/job/33788460240?pr=28765

Wonder why master isn't failing these, and why it didn't fail back in the day. Very strange thing to bitrot. Oh well.

Does not matter as long as we can get it passing consistently going forward on this branch.

**Comment by robertlong13** [comment]
Passed 9 times no issue, rebased to clean up and re-enable the other tests. When this passes, that will be 10 passes in a row.

**Comment by loki077** [comment]
@robertlong13 is this ready for review.

**Comment by robertlong13** [comment]
Yes

**Review by loki077 — APPROVED** [review]

**Pull request merged**
