### PR TITLE
CarbonixCommon: bit_esc: suppress nil warnings

### PR DESCRIPTION
**Pull request by robertlong13**
These are caused by two well-understood race conditions and we don't
need to put them up on the messages tab anymore. This will be fixed
properly in a future PR.

Also, driveby fix for resetting the nil counters. These should be done
every time we get good data, not just when recoving from telemetry loss.

### CODE REVIEW

**Comment by loki077** [comment]
@robertlong13 CRC will change too

**Comment by loki077** [comment]
Also, as the CI suggest the if statement is empty. I think lua is fine with it but not the linter.

**Comment by robertlong13** [comment]
> @robertlong13 CRC will change too

It doesn't. Modules don't count, only top-level scripts.

**Review by Pradeep-Carbonix — APPROVED** [review]
LGTM

**Review by loki077 — APPROVED** [review]
Logic Looks correct to me.

**Pull request merged**
